server: 
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nangongpushe/microservicecloud-config.git #GitHub上面的git仓库名字，这里只能够这样进行配置，否则会报错